name: macos

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [10.15, 11]

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v3

      - run: ./test.sh
